version: '3.8'

services:
  app:
    build: .
    command: python app.py
    ports:
      - "5002:5002"
    depends_on:
      - data

  data:
    build: .
    command: python data.py
    ports:
      - "5001:5001"
  nginx:
    build: .
    ports:
      - "90:90"
    depends_on:
      - app
      - data


