name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  DATA_BACKEND_IMAGE: rudrakshladdha/fast-grow-data
  COMMENT_BACKEND_IMAGE: rudrakshladdha/fast-grow-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_PROFILE }}" --password-stdin
